{{- if .Values.configmap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fcg-usuarios-api.fullname" . }}-config
  labels:
    app: {{ include "fcg-usuarios-api.name" . }}
data:
{{- range $key, $value := .Values.configmap.data }}
  {{ $key }}: "{{ $value }}"
{{- end }}
{{- end }}